#%RAML 1.0 Trait
responses:
  400:
    body:
      application/json:
        example:
          {
"code": 400,
"message": " Bad Request",
"description": "The 400 (Bad Request) status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing)",
"dateTime": "2020-05-29T05:58:02",
"transactionId": "44b32520-61ee-47b4-907d-fa15869f3c4d"
}
  500:
    body:
      application/json:
        example:
          {
          "code": 500,
          "message": "Upstream service unable to fulfil request.",
          "description": "The 500 (Internal Server Error) status code indicates that the server encountered an unexpected condition that prevented it from fulfilling the request",
          "dateTime": "2020-05-29T05:58:02",
          "transactionId": "44b65520-61ee-47b4-907d-fa06469f3c4d"
        }
  503:
    body:
      application/json:
        example:
          {
"code": 503,
"message": " Service unavailable",
"description": "The (upstream) service is temporarily notavailable",
"dateTime": "2020-05-29T05:58:02",
"transactionId": "44b32520-61ee-47b4-907d-fa15869f3c4d"
}
        
       